[package]
name = "loop_statement_008"
version = "0.1.0"
authors = ["Subin Lee <chandar.sblee@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
